[package]
name = "MAP"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2" # egui 的官方框架
image = "0.24"    # 用于读取本地图片文件

# 请确保下面这两行存在，且没有拼写错误
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"