[package]
name = "MAP"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26" # è¯·æ ¹æ®å®é™…ç‰ˆæœ¬è°ƒæ•´
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"    # ğŸ”¥ ç”¨äºè§£æç­–ç•¥æ–‡ä»¶
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
rfd = "0.12"
